# Generated by Django 4.2.18 on 2025-04-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llibre',
            name='ISBN',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
