# Generated by Django 4.2.18 on 2025-04-11 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_llibre_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llibre',
            name='ISBN',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='usuari',
            name='telefon',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Només es permeten números.', regex='^\\d+$')]),
        ),
    ]
