# Generated by Django 4.2.18 on 2025-05-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_rename_cicle_grup_rename_cicle_usuari_grup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplar',
            name='registre',
            field=models.CharField(default='EX-1970-000000', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
