# Generated by Django 4.2.18 on 2025-05-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_alter_exemplar_registre'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exemplar',
            name='unique_cataleg_exemplar',
        ),
        migrations.AddConstraint(
            model_name='exemplar',
            constraint=models.UniqueConstraint(fields=('cataleg', 'registre'), name='unique_cataleg_exemplar'),
        ),
    ]
