# Generated by Django 4.2.18 on 2025-05-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_remove_exemplar_unique_cataleg_exemplar_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exemplar',
            name='unique_cataleg_exemplar',
        ),
        migrations.AddConstraint(
            model_name='exemplar',
            constraint=models.UniqueConstraint(fields=('cataleg', 'id'), name='unique_cataleg_exemplar'),
        ),
    ]
